# Generated by Django 5.0.7 on 2024-08-16 01:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
