# Generated by Django 5.0.7 on 2024-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Biografia'),
        ),
    ]
