# Generated by Django 5.0.7 on 2024-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_registeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
